"""Add archive table

Revision ID: 89e3a2957fb7
Revises: 129feae3beda
Create Date: 2026-02-28 11:54:34.917442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e3a2957fb7'
down_revision: Union[str, None] = '129feae3beda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_batch_id_date', table_name='attendance')
    op.drop_index('ix_attendance_student_id_date', table_name='attendance')
    op.drop_index('ix_batches_session_id_status', table_name='batches')
    op.drop_index('ix_bmi_records_student_id_date', table_name='bmi_records')
    op.drop_index('ix_fees_student_id_status', table_name='fees')
    op.drop_index('ix_notifications_user_id_user_type_is_read', table_name='notifications')
    op.drop_index('ix_performance_student_id_date', table_name='performance')
    op.drop_index('ix_students_status', table_name='students')
    op.drop_column('video_resources', 'session_id')
    op.drop_column('video_resources', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_resources', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_resources', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_students_status', 'students', ['status'], unique=False)
    op.create_index('ix_performance_student_id_date', 'performance', ['student_id', 'date'], unique=False)
    op.create_index('ix_notifications_user_id_user_type_is_read', 'notifications', ['user_id', 'user_type', 'is_read'], unique=False)
    op.create_index('ix_fees_student_id_status', 'fees', ['student_id', 'status'], unique=False)
    op.create_index('ix_bmi_records_student_id_date', 'bmi_records', ['student_id', 'date'], unique=False)
    op.create_index('ix_batches_session_id_status', 'batches', ['session_id', 'status'], unique=False)
    op.create_index('ix_attendance_student_id_date', 'attendance', ['student_id', 'date'], unique=False)
    op.create_index('ix_attendance_batch_id_date', 'attendance', ['batch_id', 'date'], unique=False)
    # ### end Alembic commands ###
