"""Initial baseline

Revision ID: c70498d190af
Revises: 
Create Date: 2026-02-27 23:37:55.087919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import main
# revision identifiers, used by Alembic.
revision: str = 'c70498d190af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_batches_session_id', table_name='batches')
    op.drop_constraint('batches_session_id_fkey', 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'sessions', ['session_id'], ['id'])
    op.drop_column('coaches', 'role')
    op.drop_column('fees', 'payment_method')
    op.drop_column('fees', 'paid_date')
    op.drop_column('fees', 'collected_by')
    op.drop_constraint('invitations_invite_token_key', 'invitations', type_='unique')
    op.drop_index('ix_invitations_invite_token', table_name='invitations')
    op.create_index(op.f('ix_invitations_invite_token'), 'invitations', ['invite_token'], unique=True)
    op.create_foreign_key(None, 'student_registration_requests', 'invitations', ['invitation_id'], ['id'])
    op.create_foreign_key(None, 'student_registration_requests', 'coaches', ['invited_by_coach_id'], ['id'])
    op.alter_column('students', 'guardian_phone',
               existing_type=sa.VARCHAR(),
               type_=main.EncryptedString(),
               existing_nullable=True)
    op.drop_index('ix_video_resources_student_id', table_name='video_resources')
    op.create_index(op.f('ix_video_resources_id'), 'video_resources', ['id'], unique=False)
    op.drop_column('video_resources', 'session_id')
    op.drop_column('video_resources', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_resources', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_resources', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_resources_id'), table_name='video_resources')
    op.create_index('ix_video_resources_student_id', 'video_resources', ['student_id'], unique=False)
    op.alter_column('students', 'guardian_phone',
               existing_type=main.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'student_registration_requests', type_='foreignkey')
    op.drop_constraint(None, 'student_registration_requests', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_invite_token'), table_name='invitations')
    op.create_index('ix_invitations_invite_token', 'invitations', ['invite_token'], unique=False)
    op.create_unique_constraint('invitations_invite_token_key', 'invitations', ['invite_token'])
    op.add_column('fees', sa.Column('collected_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fees', sa.Column('paid_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fees', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coaches', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'coach'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key('batches_session_id_fkey', 'batches', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_batches_session_id', 'batches', ['session_id'], unique=False)
    # ### end Alembic commands ###
